FROM archlinux
RUN mkdir /opt/delphy-venv
ADD ./config-files/ /opt/delphy-venv/
RUN pacman -Syu --noconfirm - < /opt/delphy-venv/packages.txt
RUN groupadd -g 1000 developer
RUN useradd developer -u 1000 -g 1000 -m -s /bin/bash
VOLUME /home/developer
USER developer
WORKDIR /home/developer
ENV SHELL /bin/bash
ENV HOME /home/developer
ENV XDG_CONFIG_HOME /tmp/xdg_config 
ENV XDG_CACHE_HOME /tmp/xdg_cache
ENV XDG_DATA_HOME /tmp/xdg_data
ENV XDG_STATE_HOME /tmp/xdg_state
ENV FREEPORTS_VENV 1
ENTRYPOINT ["/bin/bash","--login"]