#!/bin/bash
export FREEPORTS_TALOS_DIR="${FREEPORTS_REPO}/talos-cluster"
export FREEPORTS_VMs_DIR="${FREEPORTS_TALOS_DIR}/.Virtual-Machines"
export FREEPORTS_VM_NAME="Talos-dev-cluster"
VBoxManage createvm --name="${FREEPORTS_VM_NAME}" --basefolder "${FREEPORTS_VMs_DIR}" --ostype="Linux_64"


VBoxManage registervm "${FREEPORTS_VMs_DIR}/${FREEPORTS_VM_NAME}.vbox"